
#runtime: python37

#handlers:
  # This configures Google App Engine to serve the files in the apps static
  # directory.
#- url: /static
#  static_dir: static

  # This handler routes all requests not caught above to your main app. It is
  # required when static routes are defined, but can be omitted (along with
  # the entire handlers section) when there are no static files defined.
#- url: /.*
#  script: auto

runtime: python
env: flex
entrypoint: gunicorn --bind 0.0.0.0:8081 slack:socketio

runtime_config:
  python_version: 3