deploy:
  provider: gae
  keyfile: details.json
  project: eighth-road-254709
before_install:
  - openssl aes-256-cbc -K $encrypted_c8faf519cee9_key -iv $encrypted_c8faf519cee9_iv -in details.json.enc -out details.json -d
