language: python
deploy:
  provider: gae
  keyfile: credentials.json
  project: eighth-road-254709
  skip_cleanup: true
  default: true

script:
    - echo 'Pass the test please.'
before_install:
    - openssl aes-256-cbc -K $encrypted_b72ac6d61e03_key -iv $encrypted_b72ac6d61e03_iv -in credentials.json.enc -out credentials.json -d

