#This is the travis ci file to do CI/CD deployments of the site when a new commit to master is pushed.
language: python
deploy:
  provider: gae
  keyfile: credentials.json
  project: eighth-road-254709
  skip_cleanup: true
  on:
    all_branches: true

script:
    - python3 env_replace.py #Running before the deployment.
before_install:
    - openssl aes-256-cbc -K $encrypted_b72ac6d61e03_key -iv $encrypted_b72ac6d61e03_iv -in credentials.json.enc -out credentials.json -d

